import { WordItem } from './types';

export const INITIAL_WORDS: WordItem[] = [
  {
    id: 'w_1',
    wordEs: 'aproximadamente',
    translationHy: 'մոտավորապես',
    pronunciation: 'ah-prohk-see-mah-dah-MEN-teh',
    category: 'Adverbios',
    categoryHy: 'Մակբայներ',
    level: 'B1',
    partOfSpeech: 'Adverbio',
    partOfSpeechHy: 'Մակբայ',
    exampleEs: 'El vuelo durará aproximadamente tres horas.',
    exampleHy: 'Թռիչքը կտևի մոտավորապես երեք ժամ։',
    synonyms: ['cerca de', 'alrededor de', 'más o menos'],
    antonyms: ['exactamente', 'precisamente'],
    definitionIntroEs: 'Indica una cifra, cantidad o tiempo aproximado sin ser exacto.',
    definitionIntroHy: 'Ցույց է տալիս մոտավոր թիվ, քանակ կամ ժամանակ:',
    usageContextEs: 'Se utiliza con frecuencia en el lenguaje hablado formal e informal para dar estimaciones.'
  },
  {
    id: 'w_2',
    wordEs: 'embarcar',
    translationHy: 'նստել (ինքնաթիռ, նավ)',
    pronunciation: 'em-bar-KAR',
    category: 'Viajes',
    categoryHy: 'Ճամփորդություններ',
    level: 'A2',
    partOfSpeech: 'Verbo',
    partOfSpeechHy: 'Բայ',
    exampleEs: 'Los pasajeros deben embarcar por la puerta cuatro.',
    exampleHy: 'Ուղևորները պետք է նստեն չորրորդ դարպասով։',
    synonyms: ['subir', 'abordar'],
    antonyms: ['desembarcar', 'bajar'],
    definitionIntroEs: 'Acción de subir a un avión, barco o transporte público.',
    definitionIntroHy: 'Ինքնաթիռ, նավ կամ տրանսպորտ բարձրանալու գործողություն:',
    usageContextEs: 'Imprescindible en aeropuertos y estaciones de tren.'
  },
  {
    id: 'w_3',
    wordEs: 'imprescindible',
    translationHy: 'անհրաժեշտ, անփոխարինելի',
    pronunciation: 'eem-preh-seen-DEE-bleh',
    category: 'Adjetivos',
    categoryHy: 'Ածականներ',
    level: 'B2',
    partOfSpeech: 'Adjetivo',
    partOfSpeechHy: 'Ածական',
    exampleEs: 'Es imprescindible llevar el pasaporte para viajar al extranjero.',
    exampleHy: 'Անհրաժեշտ է վերցնել անձնագիրը արտասահման ճամփորդելիս։',
    synonyms: ['esencial', 'vital', 'fundamental'],
    antonyms: ['prescindible', 'innecesario'],
    definitionIntroEs: 'Algo de lo que no se puede prescindir o carecer.',
    definitionIntroHy: 'Մի բան, որից հնարավոր չէ հրաժարվել:',
    usageContextEs: 'Muy usado en consejos de viaje, requisitos y recomendaciones.'
  },
  {
    id: 'w_4',
    wordEs: 'alojamiento',
    translationHy: 'կացարան, տեղավորում',
    pronunciation: 'ah-loh-hah-MYEN-toh',
    category: 'Viajes',
    categoryHy: 'Ճամփորդություններ',
    level: 'A2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Reservamos un alojamiento cerca de la plaza central.',
    exampleHy: 'Մենք կացարան ամրագրեցինք կենտրոնական հրապարակի մոտ։',
    synonyms: ['hospedaje', 'hotel', 'estancia'],
    antonyms: ['desahucio'],
    definitionIntroEs: 'Lugar donde una persona se queda temporalmente durante un viaje.',
    definitionIntroHy: 'Տեղ, որտեղ մարդը ժամանակավորապես մնում է ճամփորդության ընթացքում:',
    usageContextEs: 'Fundamental al planificar viajes y vacaciones.'
  },
  {
    id: 'w_5',
    wordEs: 'desarrollar',
    translationHy: 'զարգացնել, մշակել',
    pronunciation: 'deh-sah-rroh-LYAR',
    category: 'Trabajo',
    categoryHy: 'Աշխատանք',
    level: 'B1',
    partOfSpeech: 'Verbo',
    partOfSpeechHy: 'Բայ',
    exampleEs: 'La empresa quiere desarrollar un nuevo programa informático.',
    exampleHy: 'Ընկերությունը ցանկանում է մշակել նոր համակարգչային ծրագիր։',
    synonyms: ['crear', 'fomentar', 'progresar'],
    antonyms: ['frenar', 'destruir'],
    definitionIntroEs: 'Proceso de hacer crecer o perfeccionar una idea o proyecto.',
    definitionIntroHy: 'Գաղափար կամ նախագիծ աճեցնելու կամ կատարելագործելու գործընթաց:',
    usageContextEs: 'Muy frecuente en entornos laborales y tecnológicos.'
  },
  {
    id: 'w_6',
    wordEs: 'descuento',
    translationHy: 'զեղչ',
    pronunciation: 'des-KWEN-toh',
    category: 'Compras',
    categoryHy: 'Գնումներ',
    level: 'A1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Esta tienda ofrece un veinte por ciento de descuento.',
    exampleHy: 'Այս խանութն առաջարկում է քսան տոկոս զեղչ։',
    synonyms: ['rebaja', 'oferta', 'reducción'],
    antonyms: ['recargo', 'aumento'],
    definitionIntroEs: 'Reducción del precio original de un producto o servicio.',
    definitionIntroHy: 'Ապրանքի կամ ծառայության սկզբնական գնի նվազեցում:',
    usageContextEs: 'Común en tiendas y temporadas de rebajas.'
  },
  {
    id: 'w_7',
    wordEs: 'gastronomía',
    translationHy: 'գաստրոնոմիա, խոհանոցային արվեստ',
    pronunciation: 'gahs-troh-noh-MEE-ah',
    category: 'Comida',
    categoryHy: 'Ուտելիք',
    level: 'B1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'La gastronomía española es famosa por la paella y las tapas.',
    exampleHy: 'Իսպանական խոհանոցը հայտնի է պաելյայով և տապասներով։',
    synonyms: ['cocina', 'culinaria'],
    antonyms: [],
    definitionIntroEs: 'Conjunto de conocimientos y platos de la buena comida.',
    definitionIntroHy: 'Լավ ուտելիքի գիտելիքների և ուտեստների համախումբ:',
    usageContextEs: 'Utilizado para hablar de la cultura culinaria de un país.'
  },
  {
    id: 'w_8',
    wordEs: 'transbordo',
    translationHy: 'փոխանցում, տեղափոխում (տրանսպորտում)',
    pronunciation: 'trahns-BOR-doh',
    category: 'Transporte',
    categoryHy: 'Տրանսպորտ',
    level: 'B1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Tienes que hacer transbordo en la estación de Sol.',
    exampleHy: 'Դուք պետք է փոխեք գնացքը Սոլ կայարանում։',
    synonyms: ['cambio de tren', 'conexión'],
    antonyms: ['trayecto directo'],
    definitionIntroEs: 'Cambiar de un vehículo de transporte a otro para llegar al destino.',
    definitionIntroHy: 'Մեկ տրանսպորտային միջոցից մյուսին անցնելը տեղ հասնելու համար:',
    usageContextEs: 'Típico del metro, autobús y trenes.'
  },
  {
    id: 'w_9',
    wordEs: 'hospitalidad',
    translationHy: 'հյուրընկալություն',
    pronunciation: 'ohs-pee-tah-lee-DAD',
    category: 'España',
    categoryHy: 'Իսպանիա',
    level: 'B2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Agradecemos de corazón la gran hospitalidad del pueblo armenio.',
    exampleHy: 'Մենք ի սրտե շնորհակալ ենք հայ ժողովրդի մեծ հյուրընկալության համար։',
    synonyms: ['acogida', 'cordialidad', 'amabilidad'],
    antonyms: ['hostilidad', 'rechazo'],
    definitionIntroEs: 'Buena acogida y recibimiento que se hace a las personas visitantes.',
    definitionIntroHy: 'Այցելուներին ջերմորեն ընդունելու և հյուրասիրելու հատկություն:',
    usageContextEs: 'Expresión cultural muy valorada tanto en Armenia como en España.'
  },
  {
    id: 'w_10',
    wordEs: 'montaña',
    translationHy: 'լեռ, սար',
    pronunciation: 'mohn-TAH-nyah',
    category: 'Armenia',
    categoryHy: 'Հայաստան',
    level: 'A1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Armenia es un país famoso por sus hermosas montañas.',
    exampleHy: 'Հայաստանը հայտնի է իր գեղեցիկ լեռներով։',
    synonyms: ['cUMBRE', 'monte'],
    antonyms: ['valle', 'llanura'],
    definitionIntroEs: 'Elevación natural del terreno de gran altura.',
    definitionIntroHy: 'Բնական բարձրություն երկրի մակերևույթին:',
    usageContextEs: 'Palabra clave en descripciones geográficas y turísticas.'
  },
  {
    id: 'w_11',
    wordEs: 'mariposa',
    translationHy: 'թիթեռ',
    pronunciation: 'mah-ree-POH-sah',
    category: 'Animales',
    categoryHy: 'Կենդանիներ',
    level: 'A1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Una mariposa de colores se posó en la flor.',
    exampleHy: 'Գույնզգույն թիթեռը նստեց ծաղկի վրա։',
    synonyms: [],
    antonyms: [],
    definitionIntroEs: 'Insecto con alas grandes y a menudo de bonitos colores.',
    definitionIntroHy: 'Մեծ և գեղեցիկ թևերով միջատ:',
    usageContextEs: 'Muy común en vocabulario de naturaleza y poesía.'
  },
  {
    id: 'w_12',
    wordEs: 'arquitecto',
    translationHy: 'ճարտարապետ',
    pronunciation: 'ar-kee-TEK-toh',
    category: 'Profesiones',
    categoryHy: 'Մասնագիտություններ',
    level: 'A2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'El arquitecto diseñó un edificio moderno e iluminado.',
    exampleHy: 'Ճարտարապետը նախագծեց ժամանակակից և լուսավոր շենք։',
    synonyms: ['diseñador', 'proyectista'],
    antonyms: [],
    definitionIntroEs: 'Persona que se dedica a proyectar y construir edificios.',
    definitionIntroHy: 'Մարդ, ով զբաղվում է շենքերի նախագծմամբ և կառուցմամբ:',
    usageContextEs: 'Utilizado en temas laborales y universitarios.'
  },
  {
    id: 'w_13',
    wordEs: 'inteligencia',
    translationHy: 'ինտելեկտ, բանականություն',
    pronunciation: 'een-teh-lee-HEN-syah',
    category: 'Tecnología',
    categoryHy: 'Տեխնոլոգիա',
    level: 'B1',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'La inteligencia artificial ayuda a aprender idiomas más rápido.',
    exampleHy: 'Արհեստական ինտելեկտն օգնում է ավելի արագ լեզուներ սովորել։',
    synonyms: ['sabiduría', 'entendimiento', 'sagacidad'],
    antonyms: ['ignorancia', 'torpeza'],
    definitionIntroEs: 'Capacidad de entender, aprender y resolver problemas.',
    definitionIntroHy: 'Հասկանալու, սովորելու և խնդիրներ լուծելու ունակություն:',
    usageContextEs: 'Esencial en el mundo moderno y tecnológico.'
  },
  {
    id: 'w_14',
    wordEs: 'tormenta',
    translationHy: 'փոթորիկ, փոթորկոտ եղանակ',
    pronunciation: 'tor-MEN-tah',
    category: 'Tiempo',
    categoryHy: 'Եղանակ',
    level: 'A2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Habrá una tormenta con lluvia fuerte esta tarde.',
    exampleHy: 'Այս կեսօրին ուժեղ անձրևով փոթորիկ կլինի։',
    synonyms: ['tempestad', 'vendaval'],
    antonyms: ['calma', 'bonanza'],
    definitionIntroEs: 'Fenómeno meteorológico con lluvia, viento, rayos y truenos.',
    definitionIntroHy: 'Օդերևութաբանական երևույթ՝ անձրևով, քամիով և որոտով:',
    usageContextEs: 'Frecuente en pronósticos del tiempo.'
  },
  {
    id: 'w_15',
    wordEs: 'entusiasmo',
    translationHy: 'խանդավառություն, ոգևորություն',
    pronunciation: 'en-too-SYAS-moh',
    category: 'Sentimientos',
    categoryHy: 'Զգացմունքներ',
    level: 'B2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'Aprende español con mucho entusiasmo todos los días.',
    exampleHy: 'Նա ամեն օր մեծ ոգևորությամբ իսպաներեն է սովորում։',
    synonyms: ['ilusión', 'pasión', 'alegría'],
    antonyms: ['apatía', 'desánimo'],
    definitionIntroEs: 'Sentimiento intenso de emoción y motivación hacia algo.',
    definitionIntroHy: 'Ուժեղ հուզական վիճակ և մոտիվացիա մի բանի նկատմամբ:',
    usageContextEs: 'Común en descripciones de actitud y carácter.'
  },
  {
    id: 'w_16',
    wordEs: 'receta',
    translationHy: 'դեղատոմս / բաղադրատոմս',
    pronunciation: 'reh-SEH-tah',
    category: 'Medicina',
    categoryHy: 'Բժշկություն',
    level: 'A2',
    partOfSpeech: 'Sustantivo',
    partOfSpeechHy: 'Գոյական',
    exampleEs: 'El médico me dio una receta para los medicamentos.',
    exampleHy: 'Բժիշկն ինձ դեղատոմս տվեց դեղերի համար։',
    synonyms: ['prescripción'],
    antonyms: [],
    definitionIntroEs: 'Nota oficial médica o fórmula para cocinar un plato.',
    definitionIntroHy: 'Բժշկական պաշտոնական թուղթ կամ ուտեստ պատրաստելու ցուցում:',
    usageContextEs: 'Usado en farmacias, hospitales y también en cocina.'
  },
  {
    id: 'w_17',
    wordEs: 'recomendar',
    translationHy: 'խորհուրդ տալ, առաջարկել',
    pronunciation: 'reh-koh-men-DAR',
    category: 'Verbos',
    categoryHy: 'Բայեր',
    level: 'A2',
    partOfSpeech: 'Verbo',
    partOfSpeechHy: 'Բայ',
    exampleEs: 'Te recomiendo visitar la catedral de Toledo.',
    exampleHy: 'Խորհուրդ եմ տալիս այցելել Տոլեդոյի տաճարը։',
    synonyms: ['aconsejar', 'sugerir'],
    antonyms: ['desaconsejar'],
    definitionIntroEs: 'Aconsejar a alguien que haga algo por su bien.',
    definitionIntroHy: 'Մեկին խորհուրդ տալ մի բան անել իր օգտին:',
    usageContextEs: 'Clave para recomendaciones turísticas y profesionales.'
  },
  {
    id: 'w_18',
    wordEs: 'acogedor',
    translationHy: 'հարմարավետ, ջերմ, հյուրընկալ',
    pronunciation: 'ah-koh-heh-DOR',
    category: 'Adjetivos',
    categoryHy: 'Ածականներ',
    level: 'B1',
    partOfSpeech: 'Adjetivo',
    partOfSpeechHy: 'Ածական',
    exampleEs: 'Este café tiene un ambiente muy acogedor.',
    exampleHy: 'Այս սրճարանն ունի շատ հարմարավետ մթնոլորտ։',
    synonyms: ['cálido', 'agradable', 'confortable'],
    antonyms: ['inhóspito', 'desagradable'],
    definitionIntroEs: 'Que resulta agradable y hace sentir bienvenido.',
    definitionIntroHy: 'Հաճելի միջավայր, որը ստիպում է ձեզ ջերմ զգալ:',
    usageContextEs: 'Usado para describir hoteles, casas y lugares pintorescos.'
  },
  {
    id: 'w_19',
    wordEs: 'a pesar de',
    translationHy: 'չնայած, հակառակ',
    pronunciation: 'ah peh-SAR deh',
    category: 'Preposiciones',
    categoryHy: 'Նախդիրներ / Կապեր',
    level: 'B1',
    partOfSpeech: 'Locución prepositiva',
    partOfSpeechHy: 'Կապակցություն',
    exampleEs: 'Salimos a pasear a pesar de la lluvia.',
    exampleHy: 'Մենք գնացինք զբոսնելու՝ չնայած անձրևին։',
    synonyms: ['pese a', 'no obstante'],
    antonyms: ['debido a'],
    definitionIntroEs: 'Expresión que indica oposición o dificultad no impeditiva.',
    definitionIntroHy: 'Արտահայտություն, որը ցույց է տալիս հակառակություն կամ դժվարություն:',
    usageContextEs: 'Imprescindible para conectar oraciones complejas.'
  },
  {
    id: 'w_20',
    wordEs: 'frecuentemente',
    translationHy: 'հաճախակի, հաճախ',
    pronunciation: 'freh-kwen-teh-MEN-teh',
    category: 'Adverbios',
    categoryHy: 'Մակբայներ',
    level: 'A2',
    partOfSpeech: 'Adverbio',
    partOfSpeechHy: 'Մակբայ',
    exampleEs: 'Viajo a España frecuentemente por trabajo.',
    exampleHy: 'Ես հաճախակի եմ ճամփորդում Իսպանիա աշխատանքի բերումով։',
    synonyms: ['a menudo', 'habitualmente'],
    antonyms: ['raramente', 'pocas veces'],
    definitionIntroEs: 'Que ocurre con frecuencia o repetidamente.',
    definitionIntroHy: 'Որը տեղի է ունենում հաճախ կամ կրկնվող:',
    usageContextEs: 'Común al hablar de rutinas y hábitos.'
  },
  {
    id: 'w_21',
    wordEs: 'dar la cara',
    translationHy: 'պատասխանատվություն ստանձնել, երեսով ելնել',
    pronunciation: 'dar lah KAH-rah',
    category: 'Expresiones idiomáticas',
    categoryHy: 'Դարձվածքներ',
    level: 'B2',
    partOfSpeech: 'Expresión idiomática',
    partOfSpeechHy: 'Դարձվածք',
    exampleEs: 'Cuando cometió el error, decidió dar la cara ante su equipo.',
    exampleHy: 'Երբ նա սխալ թույլ տվեց, որոշեց պատասխանատվություն ստանձնել իր թիմի առջև։',
    synonyms: ['responder', 'asumir responsabilidad'],
    antonyms: ['esconderse', 'escaquearse'],
    definitionIntroEs: 'Afrontar las consecuencias de las propias acciones con valentía.',
    definitionIntroHy: 'Քաջաբար սեփական արարքների հետևանքներին ընդառաջ գնալ:',
    usageContextEs: 'Expresión coloquial muy usada en España y Latinoamérica.'
  },
  {
    id: 'w_22',
    wordEs: 'echar una mano',
    translationHy: 'օգնության հասնել, ձեռք մեկնել',
    pronunciation: 'eh-CHAR oo-nah MAH-noh',
    category: 'Estructuras fraseales',
    categoryHy: 'Ֆրազային կառույցներ',
    level: 'A2',
    partOfSpeech: 'Locución verbal',
    partOfSpeechHy: 'Բայական դարձվածք',
    exampleEs: '¿Me puedes echar una mano con las maletas?',
    exampleHy: 'Կարո՞ղ ես ինձ ձեռք մեկնել ճամպրուկների հարցում։',
    synonyms: ['ayudar', 'colaborar'],
    antonyms: ['estorbar'],
    definitionIntroEs: 'Ayudar amigablemente a alguien en una tarea.',
    definitionIntroHy: 'Ընկերաբար օգնել մեկին որևէ գործում:',
    usageContextEs: 'Una de las frases hechas más comunes en la vida diaria.'
  }
];
